In [1]:
import numpy as np

ModuleNotFoundError: No module named 'numpy'

In [5]:
import numpy as ars

In [13]:
a=ars.array([(1,2,3),(3,2,1)])

In [14]:
print(a)

[[1 2 3]
 [3 2 1]]


In [15]:
trans=ars.transpose(a)

In [16]:
print(trans)

[[1 3]
 [2 2]
 [3 1]]


In [17]:
trans.ravel()

array([1, 3, 2, 2, 3, 1])

In [26]:
a.reshape(6,1)

array([[1],
       [2],
       [3],
       [3],
       [2],
       [1]])

In [27]:
ze=ars.zeros((6,1))

In [28]:
print(ze)

[[0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]]


In [30]:
one=ars.ones((3,2))

In [31]:
print(one)

[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [37]:
ars.random.random((3,2))

array([[0.84182022, 0.99031365],
       [0.83409562, 0.59826787],
       [0.14466306, 0.40588232]])